modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/onVoid/Copperized/issues"


[[mods]]
modId="copperized"
version="${file.jarVersion}"
displayName="Copperized"
displayURL="https://www.curseforge.com/minecraft/mc-mods/copperized"
updateJSONURL="https://onvoid.net/copperized/update.json"
logoFile="copperized.png"
logoBlur=false
credits="onVoid"
authors="onVoid"
description="Completes copper as a worthy metalâ€”with a full set of tools, armor, doors, and a nugget."
itemIcon="copperized:copper_nugget"
configBackground="minecraft:textures/block/cut_copper.png"

[[dependencies.copperized]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
